#[[main]]
#  name = "Home"
#  url = ""
#  weight = -110

[[main]]
  parent = "Posts técnicos"
  name = "Python"
  urtl = "/tags/python/"

[[main]]
  parent = "Posts técnicos"
  name = "Pensando em Sistemas"
  url = "/tags/systemthinking/"
# Submenus are done this way: parent -> identifier
[[main]]
  parent = "Anotações"
  name = "Notes de livros"
  url = "/tags/book-insights/"
[[main]]
  parent = "Anotações"
  name = "reflexões"
  url = "/categories/reflections/"

[[main]]
  parent = "Anotações"
  name = "Livros Favoritos"
  url = "post/my-favorite-books/"

[[main]]
  parent = "Anotações"
  name = "citações favoritas"
  url = "post/saved-quotes/"

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://diogo-pessoa.github.io/"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"
