#[[main]]
#  name = "Home"
#  url = ""
#  weight = -110

[[main]]
  parent = "Posts técnicos"
  name = "Python"
  urtl = "/tags/python/"


# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://diogo-pessoa.github.io/"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"
