
# Output = things I made
[[main]]
  parent = "Output"
  name = "Reflections"
  url = "/post/reflections/"
  weight = 1

[[main]]
  parent = "Output"
  name = "Systems & Architecture"
  url = "/post/system-architecture/"
  weight = 2

[[main]]
  parent = "Output"
  name = "Python"
  url = "/post/python/"
  weight = 3

[[main]]
  parent = "Output"
  name = "CCSP Study Notes"
  url = "/post/ccsp/"
  weight = 4

[[main]]
  parent = "Output"
  name = "Cheatsheets"
  url = "/post/cheatsheets/"
  weight = 5

# Input = things I read
[[main]]
  parent = "Input"
  name = "Books to read again"
  url = "/post/books-list/"
  weight = 1

[[main]]
  parent = "Input"
  name = "Favorite Quotes"
  url = "/post/saved-quotes/"
  weight = 2

[[main]]
  parent = "Input"
  name = "Poems"
  url = "/post/poems/"
  weight = 3

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://diogo-pessoa.github.io/"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"
